
using UnityEngine;

void walk () {
    // ADD FORWARD MOVEMENT
    // ADD BACKWARD MOVEMENT
    // ADD SIDE MOVEMENT
    // ADD RIGHT DIAGONAL FORWARD MOVEMENT
    // ADD LEFT DIAGONAL FORWARD MOVEMENT
    // ADD LEFT DIAGONAL BACKWARD MOVEMENT
    // ADD RIGHT DIAGONAL BACKWARD MOVEMENT
}


